### ISSUE TITLE
请问我开启显示网速，是通过代理的上传和下载速度吗？

### ISSUE THREAD

**Issue by rlinhe** [leadscloud/ShadowsocksX-NG-R#2]
感谢作者提供这么好的工工具，我想问一下我启动ACL自动和显示网速。 这个网速的显示是通过代理的上、下载的速度，还是本机的上、下载的速度？ 

目的：就是看国内网址是不是直通

**Comment by leadscloud** [comment]
@rlinhe 不是的，是电脑上面所有的网络上传下载速度。

**Comment by leadscloud** [comment]
另外这个功能有 bug 开启后，会导致程序崩溃，它是基于 https://github.com/gjiazhe/Up-Down

**Comment by rlinhe** [comment]
> @rlinhe 不是的，是电脑上面所有的网络上传下载速度。
好的 明白了

**Comment by rlinhe** [comment]
> 另外这个功能有 bug 开启后，会导致程序崩溃，它是基于 https://github.com/gjiazhe/Up-Down

我用的挺好的

**Comment by leadscloud** [comment]
> > 另外这个功能有 bug 开启后，会导致程序崩溃，它是基于 https://github.com/gjiazhe/Up-Down
> 
> 我用的挺好的

那很好，可以说下你的系统版本信息吗，可能是在10.14上面有问题，我在原项目上面看到也有人反馈这个问题，但这个问题我没法解决。https://github.com/gjiazhe/Up-Down/issues/10

**Comment by rlinhe** [comment]
> > > 另外这个功能有 bug 开启后，会导致程序崩溃，它是基于 https://github.com/gjiazhe/Up-Down
> > 
> > 
> > 我用的挺好的
> 
> 那很好，可以说下你的系统版本信息吗，可能是在10.14上面有问题，我在原项目上面看到也有人反馈这个问题，但这个问题我没法解决。[gjiazhe/Up-Down#10](https://github.com/gjiazhe/Up-Down/issues/10)

我就是10.14，看issues说是10.13会自动关，如果你下次更新版本，ACL可以参考下这个https://github.com/ACL4SSR/ACL4SSR

**Comment by ArnoFrost** [comment]
同样我也会一段时间就崩溃 好烦,方不方便弄一个开关可以不加载这个网速呢?

**Comment by leadscloud** [comment]
@ArnoFrost 显示网速别勾选就行了，点击图标，有显示网速这个选项，默认不打开的。

**Comment by ArnoFrost** [comment]
@sbmzhcn  thanks
