### ISSUE TITLE
最新macos 随机复现ssh进程出现cpu占用飙升99%

### ISSUE THREAD

**Issue by Ryuurock** [leadscloud/ShadowsocksX-NG-R#20]
- macOS 10.15.1
- Shadowsocksx-NG-R8 1.4.6-R8(1)

随机复现ssh进程出现cpu占用飙升99%

**Comment by PetersonZhao** [comment]
- MacOS 10.14.6
- Shadowsocksx-NG-R8 1.4.6-R8 (1)

同样出现cpu占用飙升

**Comment by Ryuurock** [comment]
似乎是开全局后出现

**Comment by Gary0528** [comment]
· MAC OS Catalina 10.15 
· Shadowsocksx-NG-R8 1.4.6-R8 (1)
长时间开启，系统出现内存不足情况

**Comment by miao0405** [comment]
![Jietu20191203-095537](https://user-images.githubusercontent.com/29529645/70013749-9ae13080-15b3-11ea-9fd1-41c2e8fb5cbf.jpg)

**Comment by miao0405** [comment]
- MacOS 10.14.5（18F132)
- Shadowsocksx-NG-R8 1.4.6-R8 (1)
经常性闪退，作图时发现我的sketch老卡死，一看进程才发现，占用高达189.6%？内存压力也有十几个g??
没有全局，退出重启后状况暂时好转。

重启正常后又尝试开启全局，一开全局，占用立马飙升。

![Jietu20191203-110320](https://user-images.githubusercontent.com/29529645/70017184-7427f780-15bd-11ea-8020-e7af8f3e2cbf.jpg)
![Jietu20191203-110403](https://user-images.githubusercontent.com/29529645/70017202-7b4f0580-15bd-11ea-9a32-5d3ffebcef4e.jpg)

以上都必须强制关闭，重启，情况才有好转。

**Comment by T4di5** [comment]
卧槽这是挖矿后门调用啊

**Comment by leadscloud** [comment]
@T4di5 源代码是公开的，你可以看看是不是。

**Comment by haige268** [comment]
@leadscloud CPU这个问题能修复下吗？
