### ISSUE TITLE
更新订阅信息时，建议强制删除所有旧的节点信息，并重新展示所有节点信息

### ISSUE THREAD

**Issue by j0hnnie** [leadscloud/ShadowsocksX-NG-R#9]
为了提高易用性，建议如下：
1.强烈建议：更新订阅信息时，强制删除已有的所有节点信息（更新前的所有节点信息），并重新展示所有节点信息。
2.如果无法实现1，那么可以这样：更新订阅时以已有【相同节点地址和端口号】的同一条节点信息是否已存在，如果存在则强制更新节点信息

**Comment by leadscloud** [comment]
目前就是会删除之前的所有节点，重新更新的。

**Comment by Scyllaly** [comment]
@leadscloud 我也试过了，确实不会更新，你可以尝试一下：
当协议 由 auth_chain_a 改为 origin的时候，手动更新订阅，确实不更新

**Comment by Scyllaly** [comment]
shadowrocket会更新，不清楚为何，这个mac客户端 ssr 的混淆、协议、协议参数、混淆参数都不会更新

**Comment by Scyllaly** [comment]
勾选 打开时自动更新订阅 了，退出软件，重新打开，订阅有提示更新，节点配置信息并没有更新。

我又尝试了几遍发现了规律：
1.除非节点的备注名称改变，否则无论怎么更新订阅，节点配置信息都不变

期望得到的结果：只要更新订阅，就强制删除所有节点重新载入节点信息，无论节点备注是否有变。
